### ISSUE TITLE
About environment setup

### ISSUE THREAD

**Issue by mychina75** [avgeiss/invertible_sr#1]
Hi, Nice work~

Would you please provide environment setup information for this project?
Like tensorflow/keras version?
When I try to run test_perf_table.py, error reported. I think it should be caused by mismatch versions.

Thank you in advance.

**Comment by avgeiss** [comment]
Hi, could you post the error message please?

Here are the package versions that I am using:
keras 2.4.3
tensorflow 2.4.1
numpy 1.19.5
scipy 1.5.2
PIL 7.0.0
skimage 0.17.2

**Comment by mychina75** [comment]
Thank you for your infor. 

I tried to solve the issue after make following changes:
from keras.layers import AveragePooling2D, Conv2D, concatenate, UpSampling2D, add
==>>
from tensorflow.keras.layers import AveragePooling2D, Conv2D, concatenate, UpSampling2D, add

all keras.xxx change to tensorflow.keras.xxx

Thank you~
